=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/rules.dtd
<!--
Grammar Rules DTD
Daniel Naber (http://www.danielnaber.de), 2001-12-21, 2005-08-20

This DTD defines a format for 
 -grammar and typo rules
 -deprecated words

Note for grammar rules:

* At least one of the examples should be type="correct",
  at least one should be type="incorrect". This constraint 
  is not part of the DTD. All examples will be used
  for the test cases.
* It's often difficult to say if an error is a grammar error or
  'just' a typo, so we have no attribute for that.
-->

<!ENTITY % Languages "(en|de|pl|fr|es|it|nl|lt|uk|ru|cs|sl|sv|xx)">

<!ELEMENT rules (unification*,phrases?,category*)>
<!ATTLIST rules lang %Languages; #REQUIRED>


<!-- phrase definitions -->
<!ELEMENT unification (equivalence)+>
<!-- unification feature ID -->
<!ATTLIST unification feature ID #REQUIRED>

<!-- equivalences between features -->
<!ELEMENT equivalence (token)>
<!ATTLIST equivalence type ID #REQUIRED>

<!-- phrase definitions -->
<!ELEMENT phrases (phrase)*>

<!-- individual phrase definition -->
<!ELEMENT phrase (unify|and|token|includephrases)*>
<!ATTLIST phrase id ID #REQUIRED>

<!-- element that points to the defined phrase -->
<!ELEMENT phraseref EMPTY>
<!ATTLIST phraseref idref IDREF #REQUIRED>

<!-- OR operator for phrases -->
<!ELEMENT includephrases (phraseref)*>

<!-- Use the category element to groups rules/rulegroups: -->
<!ELEMENT category (rule|rulegroup)*>
<!-- Category name, e.g. 'Grammar', 'Spelling', 'Style' etc. -->
<!ATTLIST category name CDATA #REQUIRED>
<!-- Turns the category off or on by default -->
<!ATTLIST category default (off|on) #IMPLIED>

<!-- Use the rulegroup element to group similar 'rule' elements
that should appear as a single rule to the user: -->
<!ELEMENT rulegroup (message?,rule+)>
<!-- A unique ID for rulegroup: -->
<!ATTLIST rulegroup id ID #REQUIRED>
<!-- A short description of the error detected by this rule: -->
<!ATTLIST rulegroup name CDATA #IMPLIED>
<!-- Whether the rulegroup is switched by default off -->
<!ATTLIST rulegroup default (off|on) #IMPLIED>

<!ELEMENT rule (pattern,message,short?,example,example+)>
<!-- A unique ID for this rule (not required if this rule is inside 
a rulegroup): -->
<!ATTLIST rule id ID #IMPLIED>
<!-- A short description displayed to the user in the configuration dialog: -->
<!ATTLIST rule name CDATA #IMPLIED>
<!-- Whether the rule is switched by default off -->
<!ATTLIST rule default (off|on) #IMPLIED>

<!ELEMENT pattern (token|phraseref|and|unify)*>
<!-- Whether rules should match case-sensitively ('yes' means: 
"FOO" doesn't match "foo") -->
<!ATTLIST pattern case_sensitive (yes|no) #IMPLIED>
<!-- Where in the pattern should the error marker start, relative to the
first token of the rule. Default is mark_from="0" which means that the error
marker starts at the first token. mark_from="1" lets the marker start at the
second word etc: -->
<!ATTLIST pattern mark_from CDATA #IMPLIED>
<!-- Where in the pattern should the error marker end, relative to the
last token of the rule. Default is mark_to="0" which means that the error 
marker ends at the last token. mark_to="-1" lets the marker end one token
before the last token etc: -->
<!ATTLIST pattern mark_to CDATA #IMPLIED>

<!-- Enables logical AND between token elements. -->
<!ELEMENT and (token+)>

<!-- Enables unifying tokens -->
<!ELEMENT unify (and|token+)>
<!ATTLIST unify feature CDATA #REQUIRED>
<!ATTLIST unify type CDATA #IMPLIED>
<!-- Enables matching tokens that are not in agreement easily -->
<!ATTLIST unify negate (yes|no) "no">

<!-- token element - tokens matched by rules, could be specified as regular expressions,
regexp="yes"; postag contains any POS tags. POS tags can be specified as regular
expressions as well using postag_regexp="yes"
-->
<!ELEMENT token (#PCDATA|exception|match)*>
<!-- Is token a lemma that should be expanded? For example, "walk" would be
expanded to "walks", "walked" etc. before the rule matches if this is
set to 'yes': -->
<!ATTLIST token inflected (yes|no) "no">
<!-- Is token a regexp? -->
<!ATTLIST token regexp (yes|no) "no">
<!-- Is token negated? Set to 'yes' to make tokens match that didn't match 
before and vice versa:-->
<!ATTLIST token negate (yes|no) "no">
<!-- The part-of-speech tag of the token: -->
<!ATTLIST token postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST token postag_regexp (yes|no) "no">
<!-- Whether the postag match should be negated: -->
<!ATTLIST token negate_pos (yes|no) "no">
<!-- Maximum number of tags to skip before the match is found: -->
<!ATTLIST token skip CDATA #IMPLIED>
<!-- Is the token preceded with a whitespace? -->
<!ATTLIST token spacebefore (yes|no|ignore) "ignore">
<!-- Spaces are important for matching, leave them alone: -->
<!ATTLIST token
 xml:space (preserve) #FIXED 'preserve'>


<!-- Exception element -->
<!ELEMENT exception (#PCDATA)>
<!-- Is exception a lemma? -->
<!ATTLIST exception inflected (yes|no) "no">
<!-- Is exception a regexp? -->
<!ATTLIST exception regexp (yes|no) "no">
<!-- Is exception negated? - instead of ^ in 0.8.2 -->
<!ATTLIST exception negate (yes|no) "no">
<!-- The part-of-speech tag of the token: -->
<!ATTLIST exception postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST exception postag_regexp (yes|no) "no">
<!-- Whether the postag match should be negated: -->
<!ATTLIST exception negate_pos (yes|no) "no">
<!-- Is the exception token preceded with a whitespace? -->
<!ATTLIST exception spacebefore (yes|no|ignore) "ignore">


<!-- defines if the exception should apply to skipped tokens
i.e., the validity scope of the exception -->
<!ATTLIST exception scope (current|next|previous) "current">

<!-- Message shown to the user if a rule matches: -->
<!ELEMENT message (#PCDATA|suggestion|match)*>
<!-- Spaces are important for creating suggestions, leave them alone: -->
<!ATTLIST message
 xml:space (preserve) #FIXED 'preserve'>

<!-- short comment displayed in context menu: -->
<!ELEMENT short (#PCDATA)>

<!-- The examples are used for the unit test cases. An 'incorrect'
example is supposed to trigger an error message, in an 'correct'
example no error may be detected: -->
<!ELEMENT example (#PCDATA|marker)*>
<!-- 'triggers_error' may be used to add sentences that are known
to currently produce false alarms: -->
<!ATTLIST example type (correct|incorrect|triggers_error) #REQUIRED>
<!-- Used to explain 'triggers_error': -->
<!ATTLIST example reason CDATA #IMPLIED>
<!-- used to check if the suggested correction is correct; multiple
suggestions are joined with "|". -->
<!ATTLIST example correction CDATA #IMPLIED>
<!-- Spaces are important for testing suggestions, leave them alone: -->
<!ATTLIST example
 xml:space (preserve) #FIXED 'preserve'>

<!-- Put this around the error, i.e. the part of the text that should be
shown to the user as incorrect. This is used by the test cases to see
if the rule matches at the correct position. You can change the position
of the error marker using mark_from/mark_to (see above): -->
<!ELEMENT marker (#PCDATA)>

<!-- Suggested correction. This will be shown to the user as a possible
replacement of the text marked as an error. The test cases use this
text to replace the text between the 'marker' tags and then re-check
the text. The example with the incorrect text replace by this text
may not produde an error anymore, otherwise the test case fails: -->
<!ELEMENT suggestion (#PCDATA|match)*>

<!-- Refers to matched elements of the pattern. Can be used in
suggestions and in references in the pattern. -->
<!ELEMENT match (#PCDATA)>
<!-- Number of the matched token. -->
<!ATTLIST match no CDATA #REQUIRED>
<!-- Target POS tag, i.e., part of speech tag of the 
token that should be generated based on a given matched token -->
<!ATTLIST match postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST match postag_regexp (yes|no) "no">
<!-- Optional regular expression that specifies how the original
POS tag should be replaced in order to find a form. It is implied
that the original POS tag is defined by the 'postag' attribute.-->
<!ATTLIST match postag_replace CDATA #IMPLIED>
<!-- Optional regular expression that specifies parts in the token -->
<!ATTLIST match regexp_match CDATA #IMPLIED>
<!-- Optional regular expression that specifies how to replace the token -->
<!ATTLIST match regexp_replace CDATA #IMPLIED>
<!-- Optional attribute: how to change the case of the token: start with lower 
case, start with upper case, all letters upper case, all letters lower case -->
<!ATTLIST match case_conversion (startlower|startupper|allupper|alllower) #IMPLIED>
<!-- Optional attribute: defines if the match element should 
format a matched part of speech tag. Makes sense only inside 
the token element for refering to previous POS tags -->
<!ATTLIST match setpos (yes|no) "no">

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/xx/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rules SYSTEM "../rules.dtd">
<?xml-stylesheet type="text/xsl" href="../print.xsl" 
title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
A demo rule file for LanguageTool
Copyright (C) 2005 Daniel Naber (http://www.danielnaber.de)
$Id: grammar.xml,v 1.7 2007-05-19 17:32:03 milek_pl Exp $
-->

<rules lang="xx">

<!-- devising phrase syntax, not for production yet -->
<phrases>
	<phrase id="NP">
		<token>trivial</token>
		<token>phrase</token>
		<token>demo</token>
		<token><exception>exception</exception></token>
		</phrase>	
		<phrase id="COMPLEX_PHRASE">
		<token>complex</token>
		<includephrases>
			<phraseref idref="NP"/>
		</includephrases>
		<token>another</token>
	</phrase>
	<phrase id="DUMMY_VB1">
		<token regexp="yes">go|goa</token>
	</phrase>
	<phrase id="DUMMY_VB2">
		<token>goes</token>
	</phrase>
	<phrase id="DUMMY_VB3">
		<token>went</token>
	</phrase>
	<phrase id="COMPLEX_MULTIPLE">
		<token>first</token>
		<includephrases>
			<phraseref idref="DUMMY_VB1"/>
			<phraseref idref="DUMMY_VB2"/>
			<phraseref idref="DUMMY_VB3"/>
		</includephrases>
		<token>last</token>
	</phrase>
	<phrase id="SINGLE_TOKEN">
		<token>single</token>
	</phrase>
	<phrase id="TEST_INCLUDE">
	<token>beginning</token>
		<includephrases>
			<phraseref idref="COMPLEX_MULTIPLE"/>			
			<phraseref idref="SINGLE_TOKEN"/>
		</includephrases>
	<token>end</token>
	</phrase>
	<phrase id="trivial_include">
		<includephrases>
			<phraseref idref="DUMMY_VB1"/>
		</includephrases>
		<includephrases>
			<phraseref idref="DUMMY_VB2"/>
		</includephrases>
	</phrase>
</phrases>



  <category name="misc">

    <!-- a trivialdemo rule that matches "foo" followed by "bar" -->
    <rule id="DEMO_RULE" name="Find 'foo bar'">
      <pattern mark_from="0" case_sensitive="no">
        <token>foo</token>
        <token>bar</token>
      </pattern>
      <message>Did you mean <suggestion><match no="1"/> fuu bah</suggestion>?</message>
      <example type="correct">This is <marker>fuu bah</marker>.</example>
      <example type="incorrect" correction="foo fuu bah">This is <marker>foo bar</marker>.</example>
    </rule>

    <rule id="API_OUTPUT_TEST_RULE" name="Find 'foo bar'">
      <pattern mark_from="1" case_sensitive="no">
        <token>ach</token>
        <token>thosnaíos-sa</token>
      </pattern>
      <message>Did you mean <suggestion>fuu bah</suggestion>?</message>
      <example type="correct">This is ach <marker>fuu bah</marker>.</example>
      <example type="incorrect">This is ach <marker>thosnaíos-sa</marker>.</example>
    </rule>

    <rule id="NEGATION_TOKEN" name="test negation">
      <pattern mark_from="1">
        <token>small</token>
        <token negate="yes">test</token>
      </pattern>
      <message>test</message>
      <example type="correct">a small <marker>test</marker></example>
      <example type="incorrect">a small <marker>toast</marker></example>
    </rule>
  
  	<rule id="TEST_GO" name="another test of phrases">
		<pattern>
			<token>foo</token>
			<phraseref idref="DUMMY_VB1"/>
		</pattern>
		<message>Error!</message>
		<example type="correct">foo bar</example>
		<example type="incorrect"><marker>foo go</marker></example>
		<example type="incorrect"><marker>foo go</marker> bar</example>
		<example type="incorrect"><marker>foo goa</marker> bar</example>
		</rule>
    
    <rule id="TEST_PHRASES1" name="test phrases mechanism">
    <pattern>
    	<phraseref idref="COMPLEX_MULTIPLE"/>
    	<token>there</token>
    </pattern>
    <message>This is the matched text: <match no="1"/><match no="2"/></message>
    <example type="correct">go here</example>
    <example type="incorrect"><marker>first goes last there</marker>, please!</example>
    </rule>	

		<rule id="test_include" name="test two includeblocks">
		<pattern>
			<phraseref idref="TEST_INCLUDE"/>			
		</pattern>
		<message>Matched: <match no="1"/><match no="2"/></message>
		<example type="correct">Any string.</example>
		<example type="incorrect">Some words, <marker>beginning first go last end</marker></example>
		</rule>
			
		<rule id="test_two_phrases" name="test two phrases">
		<pattern>
			<phraseref idref="COMPLEX_MULTIPLE"/>
			<phraseref idref="SINGLE_TOKEN"/>
		</pattern>
		<message>Matched: <match no="1"/><match no="2"/></message>
		<example type="correct">Any string.</example>
		<example type="incorrect">First words and <marker>first go last</marker></example>
		</rule>  
				
		<rule id="test_and_operator" name="test logical AND">
			<pattern mark_to="-1">
				<and>
					<token regexp="yes">A.*</token>
					<token regexp="yes">[A-Z]B.*</token>
					<token negate="yes">ABC</token>
					<token regexp="yes">.*D<exception>ABED</exception></token>
				</and>
				<token>test</token>
			</pattern>
			<message>Matched: <match no="1"/></message>
			<example type="correct">CB test</example>
			<example type="correct">ABC test</example>
			<example type="incorrect"><marker>ABCD</marker> test</example>
			<example type="incorrect"><marker>ABEED</marker> test</example>
			<example type="correct"><marker>ABED</marker> test</example>
		</rule>
		
		<rule id="test_match_ref" name="testing match element...">
			<pattern>
			<token/>
			<token>by</token>
			<token><match no="0"/></token>
			</pattern>
		<message>Found \1 \2 \3.</message>
		<example type="incorrect"><marker>Step by step</marker>.</example>
		<example type="correct">blabla</example>
		<example type="correct">Steb by step</example>
		</rule>
		
		<rule id="test_match_ref_superb" name="testing match element on steroids...">
			<pattern>
			<token/>
			<token>by</token>
			<token><match no="0"/>on</token>
			</pattern>
		<message>Found \1 \2 \3.</message>
		<example type="correct"><marker>Step by step</marker>.</example>
		<example type="incorrect"><marker>Step by stepon</marker>.</example>
		<example type="correct">blabla</example>
		<example type="correct">Steb by step</example>
		</rule>
		
		
  </category>

</rules>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/ru/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "../rules.dtd">
<?xml-stylesheet type="text/xsl" href="../print.xsl" 
title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
A Russian rule file for LanguageTool
Copyright (C) 2005 Daniel Naber (http://www.danielnaber.de)
Copyright (C) 2008 Yakov Reztsov
$Id: grammar.xml,v 1.2 2008-05-04 21:27:29 milek_pl Exp $
-->
<rules lang="ru">
    <category name="Пунктуация">
        <rulegroup id="POZHALUJSTA" name="«пожалуйста» выделяется запятыми">
            <rule>
                <pattern mark_to="0">
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token>пожалуйста</token>
                </pattern>
                <message>Нет запятой: <suggestion>\1, \2</suggestion>.</message>
                <example type="correct">Закройте дверь, <marker>пожалуйста.</marker></example>
                <example type="incorrect">Закройте <marker>дверь пожалуйста</marker>.</example>
            </rule>
        </rulegroup>
        <rulegroup id="KAK_PRAVILO" name="Вводное сочетание как обычно, как всегда, ...">
            <!--Вводное сочетание как обычно, как всегда, как правило, как исключение, как сейчас, как нарочно
-->
            <rule>
                <pattern>
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token>как</token>
                    <token regexp="yes">обычно|всегда|правило|исключение|нарочно|сейчас</token>
                </pattern>
                <message>Нет запятой: <suggestion>\1, \2 \3,</suggestion>.</message>
                <example type="correct">Мы<marker>, как правило,</marker> ходим в походы летом.</example>
                <example type="incorrect" correction="Мы, как правило,"><marker>Мы как правило</marker> ходим в походы летом.</example>
            </rule>         
        </rulegroup>
        <rulegroup id="KAK_I" name="После союза как следует и">
 <!--TODO: Detect 2 comma.-->
                <rule>
                <pattern>
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token>как</token>
                    <token>и</token>
                </pattern>
                <message>Оборот "как и" выделяется запятыми: <suggestion>\1, \2 \3 </suggestion>.</message>
                <example type="correct">Мы<marker>, как и наши товарищи,</marker> любим заниматься спортом.</example>
                <example type="incorrect"><marker>Мы как и</marker> наши товарищи любим заниматься спортом.</example>
            </rule>
        </rulegroup>
        <rulegroup default="on" id="A_NO_DA" name="Союзы 'а, но'">
            <rule>
                <pattern>
                    <token negate="yes">,</token>
                    <token>а</token>
                </pattern>
                <message>Запятая пропущена здесь:<suggestion>\1, \2</suggestion>.</message>
                <example type="correct">И растёт ребёнок там не по дням, а по часам.</example>
                <example type="incorrect">И растёт ребёнок там не по <marker>дням а</marker> по часам.</example>
            </rule>
            <rule>
                <pattern>
                    <token negate="yes">,</token>
                    <token>но</token>
                </pattern>
                <message>Запятая пропущена здесь:<suggestion>\1, \2</suggestion>.</message>
                <example type="correct">Она говорила мало, но толково.</example>
                <example type="incorrect">Она говорила <marker>мало но</marker> толково.</example>
            </rule>
        </rulegroup>
        <rulegroup default="on" id="VVODNOE_SLOVO" name="Вводные слова: по-видимому, ...">
            <rule>
                <pattern>
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token regexp="yes">по-видимому|по-моему</token>
                </pattern>
                <message>Запятая пропущена здесь:<suggestion>\1, \2,</suggestion>.</message>
                <example type="correct">Это показалось ему, по-видимому, странным.</example>
                <example type="incorrect" correction="ему, по-видимому,">Это показалось <marker>ему по-видимому</marker> странным.</example>
            </rule>
        </rulegroup>
        
        <rulegroup default="on" id="PREDLOGI_KROME" name="Дополнения, вводимые предлогами: кроме, ...">
            <!--Дополнения, вводимые предлогами: кроме, помимо, вместо, сверх, за исключением
            --> 
 <!--TODO: Detect 2 comma.-->
            <rule>
                <pattern>
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token regexp="yes">кроме|помимо|вместо|сверх</token>
                </pattern>
                <message>Запятая пропущена здесь:<suggestion>\1, \2</suggestion></message>
                <example type="correct">Около костра, кроме Ивана, грелось ещё пять человек.</example>
                <example type="incorrect">Около <marker>костра кроме</marker> Ивана грелось ещё пять человек.</example>
            </rule>   
            <rule>
                <pattern>
                    <token negate="yes" regexp="yes">,|\.</token>
                    <token>за</token>
                    <token>исключением</token>
                </pattern>
                <message>Запятая пропущена здесь:<suggestion>\1, \2 \3</suggestion></message>
                <example type="correct">В поход, за исключением Ивана, пошло ещё пять человек.</example>
                <example type="incorrect" correction="поход, за исключением">В <marker>поход за исключением</marker> Ивана пошло ещё пять человек.</example>
            </rule>
        </rulegroup>
        <rulegroup default="on" id="NO_KAK_POPALO" name="Что угодно, как попало">
            <!--Что угодно, как попало  не выделяются запятыми.
            --> 
            <rule>
                <pattern>
                    <token  regexp="yes">,</token>
                    <token  regexp="yes">что|как</token>
                    <token  regexp="yes">попало|угодно</token>
                </pattern>
                <message>Запятая не нужна:<suggestion> \2 \3</suggestion></message>
                <example type="correct">Работа была сделана как попало.</example>
                <example type="incorrect">Работа была сделана<marker>, как попало</marker>.</example>
            </rule>
        </rulegroup>
        <rulegroup default="on" id="NO_NE_KAK" name="Почти как, не как, ...">
            <!--Перед сравнительным оборотом стоит не или слова совсем, совершенно, почти, именно запятая не ставится.
            --> 
            <rule>
                <pattern>
                    <token  regexp="yes">не|совсем|совершенно|почти|именно</token>
                    <token  regexp="yes">,</token>
                    <token>как</token>
                </pattern>
                <message>Запятая не нужна:<suggestion> \1 \3</suggestion></message>
                <example type="correct">Работа была сделана совсем как попало.</example>
                <example type="incorrect">Работа была сделана <marker>совсем, как</marker> попало.</example>
            </rule>
        </rulegroup>
        <rulegroup default="on" id="NO_NE_TO_CHTO" name="Не то что, не так чтобы, не иначе как">
            <!-- Внутри сочетаний не то что, не то (так) чтобы, не иначе как запятая не ставится.
            --> 
            <rule>
                <pattern>
                    <token>не</token>
                    <token  regexp="yes">то|иначе|так</token>
                     <token  regexp="yes">,</token>
                    <token  regexp="yes">что|как|чтобы</token>                    
                </pattern>
                <message>Запятая не нужна:<suggestion>\1 \2 \4</suggestion></message>
                <example type="correct">Работа была сделана не иначе как полностью.</example>
                <example type="incorrect">Работа была сделана <marker>не иначе, как</marker> полностью.</example>
            </rule>
        </rulegroup>
    </category>   
    <category name="Типографика">
        <rule default="off"  id="KAVITCHKI" name="„ → ”">
            <pattern>
                <token>“</token>
            </pattern>
            <message>Кавычки не соответствуют нормам типографики.  Должно быть: <suggestion>„</suggestion>пример<suggestion>”</suggestion>.</message>
            <example type="correct">Газета „Правда”.</example>
            <example correction="„|”" type="incorrect">Газета <marker>“</marker>Правда”.</example>
        </rule>
    </category>    
</rules>
