=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/rules.dtd
<!--
Grammar Rules DTD
Daniel Naber (http://www.danielnaber.de), 2001-12-21, 2005-08-20

This DTD defines a format for 
 -grammar and typo rules
 -deprecated words

Note for grammar rules:

* At least one of the examples should be type="correct",
  at least one should be type="incorrect". This constraint 
  is not part of the DTD. All examples will be used
  for the test cases.
* It's often difficult to say if an error is a grammar error or
  'just' a typo, so we have no attribute for that.
-->

<!ENTITY % Languages "(en|de|pl|fr|es|it|nl|lt|uk|ru|cs|sl|sv|xx)">

<!ELEMENT rules (unification*,phrases?,category*)>
<!ATTLIST rules lang %Languages; #REQUIRED>


<!-- phrase definitions -->
<!ELEMENT unification (equivalence)+>
<!-- unification feature ID -->
<!ATTLIST unification feature ID #REQUIRED>

<!-- equivalences between features -->
<!ELEMENT equivalence (token)>
<!ATTLIST equivalence type ID #REQUIRED>

<!-- phrase definitions -->
<!ELEMENT phrases (phrase)*>

<!-- individual phrase definition -->
<!ELEMENT phrase (unify|and|token|includephrases)*>
<!ATTLIST phrase id ID #REQUIRED>

<!-- element that points to the defined phrase -->
<!ELEMENT phraseref EMPTY>
<!ATTLIST phraseref idref IDREF #REQUIRED>

<!-- OR operator for phrases -->
<!ELEMENT includephrases (phraseref)*>

<!-- Use the category element to groups rules/rulegroups: -->
<!ELEMENT category (rule|rulegroup)*>
<!-- Category name, e.g. 'Grammar', 'Spelling', 'Style' etc. -->
<!ATTLIST category name CDATA #REQUIRED>
<!-- Turns the category off or on by default -->
<!ATTLIST category default (off|on) #IMPLIED>

<!-- Use the rulegroup element to group similar 'rule' elements
that should appear as a single rule to the user: -->
<!ELEMENT rulegroup (message?,rule+)>
<!-- A unique ID for rulegroup: -->
<!ATTLIST rulegroup id ID #REQUIRED>
<!-- A short description of the error detected by this rule: -->
<!ATTLIST rulegroup name CDATA #IMPLIED>
<!-- Whether the rulegroup is switched by default off -->
<!ATTLIST rulegroup default (off|on) #IMPLIED>

<!ELEMENT rule (pattern,message,short?,example,example+)>
<!-- A unique ID for this rule (not required if this rule is inside 
a rulegroup): -->
<!ATTLIST rule id ID #IMPLIED>
<!-- A short description displayed to the user in the configuration dialog: -->
<!ATTLIST rule name CDATA #IMPLIED>
<!-- Whether the rule is switched by default off -->
<!ATTLIST rule default (off|on) #IMPLIED>

<!ELEMENT pattern (token|phraseref|and|unify)*>
<!-- Whether rules should match case-sensitively ('yes' means: 
"FOO" doesn't match "foo") -->
<!ATTLIST pattern case_sensitive (yes|no) #IMPLIED>
<!-- Where in the pattern should the error marker start, relative to the
first token of the rule. Default is mark_from="0" which means that the error
marker starts at the first token. mark_from="1" lets the marker start at the
second word etc: -->
<!ATTLIST pattern mark_from CDATA #IMPLIED>
<!-- Where in the pattern should the error marker end, relative to the
last token of the rule. Default is mark_to="0" which means that the error 
marker ends at the last token. mark_to="-1" lets the marker end one token
before the last token etc: -->
<!ATTLIST pattern mark_to CDATA #IMPLIED>

<!-- Enables logical AND between token elements. -->
<!ELEMENT and (token+)>

<!-- Enables unifying tokens -->
<!ELEMENT unify (and|token+)>
<!ATTLIST unify feature CDATA #REQUIRED>
<!ATTLIST unify type CDATA #IMPLIED>
<!-- Enables matching tokens that are not in agreement easily -->
<!ATTLIST unify negate (yes|no) "no">

<!-- token element - tokens matched by rules, could be specified as regular expressions,
regexp="yes"; postag contains any POS tags. POS tags can be specified as regular
expressions as well using postag_regexp="yes"
-->
<!ELEMENT token (#PCDATA|exception|match)*>
<!-- Is token a lemma that should be expanded? For example, "walk" would be
expanded to "walks", "walked" etc. before the rule matches if this is
set to 'yes': -->
<!ATTLIST token inflected (yes|no) "no">
<!-- Is token a regexp? -->
<!ATTLIST token regexp (yes|no) "no">
<!-- Is token negated? Set to 'yes' to make tokens match that didn't match 
before and vice versa:-->
<!ATTLIST token negate (yes|no) "no">
<!-- The part-of-speech tag of the token: -->
<!ATTLIST token postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST token postag_regexp (yes|no) "no">
<!-- Whether the postag match should be negated: -->
<!ATTLIST token negate_pos (yes|no) "no">
<!-- Maximum number of tags to skip before the match is found: -->
<!ATTLIST token skip CDATA #IMPLIED>
<!-- Is the token preceded with a whitespace? -->
<!ATTLIST token spacebefore (yes|no|ignore) "ignore">
<!-- Spaces are important for matching, leave them alone: -->
<!ATTLIST token
 xml:space (preserve) #FIXED 'preserve'>


<!-- Exception element -->
<!ELEMENT exception (#PCDATA)>
<!-- Is exception a lemma? -->
<!ATTLIST exception inflected (yes|no) "no">
<!-- Is exception a regexp? -->
<!ATTLIST exception regexp (yes|no) "no">
<!-- Is exception negated? - instead of ^ in 0.8.2 -->
<!ATTLIST exception negate (yes|no) "no">
<!-- The part-of-speech tag of the token: -->
<!ATTLIST exception postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST exception postag_regexp (yes|no) "no">
<!-- Whether the postag match should be negated: -->
<!ATTLIST exception negate_pos (yes|no) "no">
<!-- Is the exception token preceded with a whitespace? -->
<!ATTLIST exception spacebefore (yes|no|ignore) "ignore">


<!-- defines if the exception should apply to skipped tokens
i.e., the validity scope of the exception -->
<!ATTLIST exception scope (current|next|previous) "current">

<!-- Message shown to the user if a rule matches: -->
<!ELEMENT message (#PCDATA|suggestion|match)*>
<!-- Spaces are important for creating suggestions, leave them alone: -->
<!ATTLIST message
 xml:space (preserve) #FIXED 'preserve'>

<!-- short comment displayed in context menu: -->
<!ELEMENT short (#PCDATA)>

<!-- The examples are used for the unit test cases. An 'incorrect'
example is supposed to trigger an error message, in an 'correct'
example no error may be detected: -->
<!ELEMENT example (#PCDATA|marker)*>
<!-- 'triggers_error' may be used to add sentences that are known
to currently produce false alarms: -->
<!ATTLIST example type (correct|incorrect|triggers_error) #REQUIRED>
<!-- Used to explain 'triggers_error': -->
<!ATTLIST example reason CDATA #IMPLIED>
<!-- used to check if the suggested correction is correct; multiple
suggestions are joined with "|". -->
<!ATTLIST example correction CDATA #IMPLIED>
<!-- Spaces are important for testing suggestions, leave them alone: -->
<!ATTLIST example
 xml:space (preserve) #FIXED 'preserve'>

<!-- Put this around the error, i.e. the part of the text that should be
shown to the user as incorrect. This is used by the test cases to see
if the rule matches at the correct position. You can change the position
of the error marker using mark_from/mark_to (see above): -->
<!ELEMENT marker (#PCDATA)>

<!-- Suggested correction. This will be shown to the user as a possible
replacement of the text marked as an error. The test cases use this
text to replace the text between the 'marker' tags and then re-check
the text. The example with the incorrect text replace by this text
may not produde an error anymore, otherwise the test case fails: -->
<!ELEMENT suggestion (#PCDATA|match)*>

<!-- Refers to matched elements of the pattern. Can be used in
suggestions and in references in the pattern. -->
<!ELEMENT match (#PCDATA)>
<!-- Number of the matched token. -->
<!ATTLIST match no CDATA #REQUIRED>
<!-- Target POS tag, i.e., part of speech tag of the 
token that should be generated based on a given matched token -->
<!ATTLIST match postag CDATA #IMPLIED>
<!-- Whether the string in 'postag' is a regular expression: -->
<!ATTLIST match postag_regexp (yes|no) "no">
<!-- Optional regular expression that specifies how the original
POS tag should be replaced in order to find a form. It is implied
that the original POS tag is defined by the 'postag' attribute.-->
<!ATTLIST match postag_replace CDATA #IMPLIED>
<!-- Optional regular expression that specifies parts in the token -->
<!ATTLIST match regexp_match CDATA #IMPLIED>
<!-- Optional regular expression that specifies how to replace the token -->
<!ATTLIST match regexp_replace CDATA #IMPLIED>
<!-- Optional attribute: how to change the case of the token: start with lower 
case, start with upper case, all letters upper case, all letters lower case -->
<!ATTLIST match case_conversion (startlower|startupper|allupper|alllower) #IMPLIED>
<!-- Optional attribute: defines if the match element should 
format a matched part of speech tag. Makes sense only inside 
the token element for refering to previous POS tags -->
<!ATTLIST match setpos (yes|no) "no">

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/da/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "../rules.dtd" >
<?xml-stylesheet type="text/xsl" href="../print.xsl" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
Danish Grammar and Typo Rules for LanguageTool
See danish_tags.txt for the meaning of the POS tags
Copyright (C) 2009 Esben Aaberg, Foreningen for frit tilgængelige sprogværktøjer
$Id: grammar.xml,v 1.1 2009-10-08 21:46:24 dnaber Exp $
-->
<rules lang="da">
  <!-- ====================================================================== -->
  <!-- Diverse - Misc -->
  <!-- ====================================================================== -->
  <category name="Diverse">
     <rulegroup id="OrdgentagelseGroup" name="Ordgentagelse">
        <rule id="Ordgentagelse">
           <pattern>
              <token><exception postag="SENT_START"/></token>
              <token><match no="0"/><exception regexp="yes">.|av|bang|bred|bib|bip|bling|bom|bro|duer|fars|faster|fatter|gak|grynt|ha|he|hej|hi|hip|ho|hopper|hurra|kvier|led|marie|men|mobil|mors|normal|original|piller|rap|ren|ride|sej|smed|så|taget|takker|tik-tak|tog|tut|uniform|vov|øf</exception></token>
           </pattern>
           <message>Ordgentagelse: Du har gentaget <suggestion>\1</suggestion>.</message>
           <short>Ordgentagelse</short>
           <example type="incorrect">Nu har <marker>jeg jeg</marker> aldrig hørt magen.</example>
           <example type="correct">Så så drengen en drage.</example>
           <example type="correct">Han har taget taget af hundehuset.</example>
           <example type="correct">"Rap rap" sagde anden.</example>
        </rule>
     </rulegroup>
  </category>
  <!-- ====================================================================== -->
  <!-- Mulig slåfejl - Possible Typos -->
  <!-- ====================================================================== -->
  <category name="Mulige slåfejl">
    <rule id="bindestreg_og" name="Manglende mellemrum efter bindestreg">
      <pattern>
        <token regexp="yes">(.*)-(og|eller)</token>
      </pattern>
      <message>Mulig slåfejl manglende mellemrum efter bindestreg: <suggestion><match no="1" regexp_match="(.*)-(og|eller)" regexp_replace="$1- $2"/></suggestion>.</message>
      <short>Mulig slåfejl</short>
      <example type="correct">Vi skal på oplevelses- eller badeferie.</example>
      <example correction="oplevelses- eller" type="incorrect">Vi skal på <marker>oplevelses-eller</marker> badeferie.</example>
      <example type="correct">De er <marker>hus- og</marker> haveejere.</example>
      <example correction="hus- og" type="incorrect">De er <marker>hus-og</marker> haveejere.</example>
    </rule>
  </category>
  <!-- ====================================================================== -->
  <!-- Mulig ordforveksling - Possible word confusion -->
  <!-- ====================================================================== -->
  <category name="Mulige ordforveksling">
  <!-- 
    <rule id="heder_hedder" name="heder→hedder">
      <pattern mark_from="1" mark_to="-1"> 
        <token regexp="yes">I|jeg|du|vi|de|den|det|han|hun|hvad|nu</token>
        <token>heder</token>
        <token><exception regexp="yes">på|vil|skal|kan|er|har</exception></token>
      </pattern>
      <message>Mente du: <suggestion>hedder</suggestion>=navn eller heder=lyngarealer</message>
      <short>Mulig slåfejl</short>
      <example correction="hedder" type="incorrect">Jeg <marker>heder</marker> Jens.</example>
      <example correction="hedder" type="incorrect">Det <marker>heder</marker> på Sjælland, da det er en ø.</example>
      <example type="correct">Jeg hedder Jens.</example>
      <example type="correct">De heder på landet er bevaringsværdige.</example>
      <example type="correct">Jeg heder vil vandre.</example>
    </rule>
     -->
    <rule id="heder_hedder2" name="heder→hedder Egenavn efter">
      <pattern mark_from="1" mark_to="-1">
	<token><exception regexp="yes">de</exception></token> 
        <token>heder</token>
        <token postag="pro:.*" postag_regexp="yes"/>
      </pattern>
      <message>Mente du: <suggestion>hedder</suggestion>=navn eller heder=lyngarealer</message>
      <short>Mulig slåfejl</short>
      <example correction="hedder" type="incorrect">Jeg <marker>heder</marker> Jens.</example>
      <example type="correct">Jeg hedder Jens.</example>
      <example type="correct">De heder Jens passer.</example>      
    </rule>
    <rule id="heder_hedder3" name="heder→hedder Egenavn før">
      <pattern mark_from="1">
	<token postag="pro:nom" postag_regexp="yes"/>
        <token>heder</token>        
      </pattern>
      <message>Mente du: <suggestion>hedder</suggestion>=navn eller heder=lyngarealer</message>
      <short>Mulig slåfejl</short>
      <example correction="hedder" type="incorrect">Peder <marker>heder</marker> Sørnsen til efternavn.</example>
      <example type="correct">Peter hedder Sørnsen til efternavn.</example>
      <example type="correct">Peters heder er vel plejet.</example>      
    </rule>
    <rulegroup id="natural_naturel" name="natural→naturel">
      <rule>
        <pattern mark_from="0" mark_to="-1">
          <token>natural</token>
          <token regexp="yes">yoghurt|tun|hummer|a38|Aloe|flødeost|soya|tufu|ylette|østers|krabbekød</token>
        </pattern>
        <message>Mente du: <suggestion>naturel</suggestion>=i sin naturlige, ubearbejdede, rene form især om mad</message>
        <short>Mulige ordforveksling</short>
        <example correction="naturel" type="incorrect">Opskrifter som indeholder <marker>natural</marker> yoghurt.</example>
        <example type="correct">Tufu naturel restaurationen.</example>
        <example type="correct">Opskrifter som indeholder naturel yoghurt.</example> 
      </rule>
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">yoghurt|tun|hummer|contrat|a38|Vera|flødeost|soya|tufu|ylette|østers|krabbekød</token>
          <token>natural</token>
        </pattern>
        <message>Mente du: <suggestion>naturel</suggestion>=i sin naturlige, ubearbejdede, rene form især om mad</message>
        <short>Mulige ordforveksling</short>
        <example correction="naturel" type="incorrect">Opskrifter som indeholder Yoghurt <marker>natural</marker>.</example>
        <example type="correct">Restaurationen byder på både gratineret hummer og hummer naturel.</example>
        <example type="correct">Opskrifter som indeholder Yoghurt naturel.</example> 
      </rule>
    </rulegroup>
  </category>
  <!-- ====================================================================== -->
  <!-- Mulig ordforveksling med sjældent ord - Possible word confusion with rare words -->
  <!-- ====================================================================== -->
  <category name="Mulige ordforveksling med sjældent ord">
    <rule id="standart_standard" name="standart→standard">
      <pattern mark_from="0"> 
        <token regexp="yes">.*standart.*</token>
      </pattern>
      <message>Mente du: <suggestion><match no="1" regexp_match="(.*)standart(.*)" regexp_replace="$1standard$2"/></suggestion> som standard=niveau, procedure, el. norm eller standart=fane</message>
      <short>Mulige ordforveksling</short>
      <example correction="dokumentstandard" type="incorrect">Den der <marker>dokumentstandart</marker> følger vi.</example>
      <example type="correct">Den der dokumentstandard følger vi.</example>
    </rule>
  </category>
  <!-- ====================================================================== -->
  <!-- Forkortelser med eller uden punktum - abbreviation -->
  <!-- ====================================================================== -->
  <!-- 
  <category name="Forkortelser med eller uden punktum">
    <rule id="fx" name="fx.→fx">
      <pattern mark_from="0" > 
        <token>fx</token>
        <token>.</token>
      </pattern>
      <message>For eksempel forkortes <suggestion>fx</suggestion> uden punktum eller <suggestion>f.eks.</suggestion></message>      
      <short>Mulig overflødigt punktum</short>
      <example correction="fx" type="incorrect">Som <marker>fx.</marker> jern.</example>
      <example type="correct">Som fx jern.</example>
      <example type="correct">Som f.eks. jern.</example>
    </rule>
  </category>
   -->
  <!-- ====================================================================== -->
  <!-- Grammatik - Grammar -->
  <!-- ====================================================================== -->
  <category name="Grammatik">
    <rule id="adj:ube:sin:utr:pos" name="Tillægsord ental ubestemt i forkert bøjningsform">
      <pattern mark_from="1" > 
        <token regexp="yes">et|det</token>
        <!-- TODO: Make exception for adverbs, when they becomes available in tagger -->
        <token postag="adj:ube:sin:utr:pos" postag_regexp="yes" regexp="yes">.*[a-s,u-å]<exception postag="sub:.*:neu:.*" postag_regexp="yes" regexp="yes">før</exception></token>
      </pattern>
      <message>Ved at der står "\1" skal tilægsord <suggestion>\2t</suggestion> være intetkøn</message>      
      <short>Muligvis tillægsord i forker form</short>
      <example correction="syndigt" type="incorrect">Et <marker>syndig</marker> rod.</example>
      <example correction="ovalt" type="incorrect">Det er et <marker>oval</marker> køkkenbord.</example>
      <example type="correct">Det er et ret visende eksempel.</example>
      <example type="correct">Et syndigt rod.</example>
      <example type="correct">Tidligere var det syndigt at vise sine ankler.</example>
    </rule>
  </category>
</rules>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/it/grammar.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rules SYSTEM "../rules.dtd">
<?xml-stylesheet type="text/xsl" href="../print.xsl" 
title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
Italian Grammar and Typo Rules for LanguageTool
Copyright (C) 2006 Marcin Miłkowski
$Id: grammar.xml,v 1.4 2009-03-11 21:07:56 dnaber Exp $
-->
<rules lang="it">

  <category name="misc">

	 <rule id="A_GRATIS" name="«a gratis» (gratis)">
      <pattern mark_from="0" case_sensitive="no">
        <token>a</token>
        <token>gratis</token>
      </pattern>
      <message>Si scrive <suggestion>gratis</suggestion> (senza la preposizione).</message>
      <example type="correct">Ovviamente... è tutto <marker>gratis</marker>!</example>
      <example type="incorrect">Ovviamente... è tutto <marker>a gratis</marker>!</example>
    </rule>
	
	  <rule id="PIU_MOLTO" name="«più molto» (di più)">
		  <pattern>
			  <token>più</token>
			  <token>molto</token>
		  </pattern>
		  <message>E' un errore creare il comparativo di maggioranza degli avverbi molto e poco. Si scrive <suggestion>di più</suggestion>.</message>
		  <example type="incorrect">Il calcio mi piace, ma il motociclismo mi piace <marker>più molto</marker>.</example>
		  <example type="correct">Il calcio mi piace, ma il motociclismo mi piace di più.</example>
	  </rule>
		
	  <rule id="PIU_POCO" name="«più poco» (meno)">
		  <pattern>
			  <token>più</token>
			  <token>poco</token>
		  </pattern>
		  <message>E' un errore creare il comparativo di maggioranza degli avverbi molto e poco. Si scrive <suggestion>meno</suggestion>.</message>
		  <example type="incorrect">Stasera abbiamo ballato <marker>più poco</marker> del solito.</example>
		  <example type="correct">Stasera abbiamo ballato meno del solito.</example>
	  </rule>  
  </category>

  <category name="Pleonasmi">
	  <rule id="A_ME_MI" name="«a me mi» (mi)">
		  <pattern>
			  <token>a</token>
			  <token regexp="yes">me|noi</token>
			  <token regexp="yes">mi|ci</token>
		  </pattern>
		  <message>Si tratta di una ripetizione. Meglio scegliere una delle due forme: <suggestion>a me</suggestion> <suggestion>a noi</suggestion>oppure <suggestion>mi</suggestion> <suggestion>ci</suggestion>.</message>
		  <example type="incorrect"><marker>A me mi</marker> piace il gelato.</example>
		  <example type="correct">Mi piace il gelato.</example>
	  </rule>

	  <rule id="A_TE_TI" name="«a te ti» (ti)">
		  <pattern>
			  <token>a</token>
			  <token regexp="yes">te|voi</token>
			  <token regexp="yes">ti|vi</token>
		  </pattern>
		  <message>Si tratta di una ripetizione. Meglio scegliere una delle due forme: <suggestion>a te</suggestion> <suggestion>a voi</suggestion>oppure <suggestion>ti</suggestion> <suggestion>vi</suggestion>.</message>
		  <example type="incorrect"><marker>A te ti</marker> pare strano.</example>
		  <example type="correct">Ti pare strano.</example>
	  </rule>

	  <rule id="A_LUI_GLI" name="«a lui gli» (gli)">
		  <pattern>
			  <token>a</token>
			  <token regexp="yes">lui|lei</token>
			  <token regexp="yes">gli|le</token>
		  </pattern>
		  <message>Si tratta di una ripetizione. Meglio scegliere una delle due forme: <suggestion>a te</suggestion> <suggestion>a lei</suggestion> oppure <suggestion>gli</suggestion>.</message>
		  <example type="incorrect"><marker>A lui gli</marker> faceva comodo.</example>
		  <example type="correct">Gli faceva comodo.</example>
	  </rule>

	  <rule id="A_LORO_GLI" name="«a loro gli» (gli)">
		  <pattern>
			  <token>a</token>
			  <token>loro</token>
			  <token>gli</token>
		  </pattern>
		  <message>Si tratta di una ripetizione. Meglio scegliere una delle due forme: <suggestion>a loro</suggestion> oppure <suggestion>gli</suggestion>.</message>
		  <example type="incorrect"><marker>A loro gli</marker> tornava utile.</example>
		  <example type="correct">Gli tornava utile.</example>
	  </rule>

  </category>	

  <category name="Accenti">
	  <rule name="da (dà)" id="DA_DA_ACCENTO">
		<pattern mark_from="1">
			<token postag_regexp="yes" postag="PRO-PERS-CLI.*"/>
			<token>da</token>
		</pattern>
		 <message>Probabilmente si escrive con accento: <suggestion>dà</suggestion>.</message>
  		 <example type="incorrect">Luigi mi <marker>da</marker> la mano.</example>
		 <example type="correct">Luigi mi dà la mano.</example>
	  </rule>	  
	  <rule name="dà (da)" id="DA_ACCENTO_DA">
		<pattern mark_from="1">
			<token postag_regexp="yes" postag="VER:ind.*"/>
			<token>dà</token>
		</pattern>
		 <message>Probabilmente si escrive senza accento: <suggestion>da</suggestion>.</message>
  		 <example type="incorrect">Vengo <marker>dà</marker> Roma.</example>
		 <example type="correct">Vengo da Roma.</example>
	  </rule>
  </category>
</rules>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/es/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rules SYSTEM "../rules.dtd">
<?xml-stylesheet type="text/xsl" href="../print.xsl" 
title="Pretty print" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
Spanish Grammar and Typo Rules for LanguageTool
Copyright (C) 2006 Marcin Miłkowski
$Id: grammar.xml,v 1.7 2009-09-21 10:21:28 milek_pl Exp $
-->
<rules lang="es">
  <category name="misc">
    <!-- from Spanish Wikipedia -->
    <rule id="DE_GRATIS" name="«de gratis» (gratis)">
      <pattern case_sensitive="no" mark_from="0">
        <token>de</token>
        <token>gratis</token>
      </pattern>      
      <message>La forma correcta es decir <suggestion>gratis</suggestion>.</message>
      <short>Forma incorrecta</short>
      <example type="correct">El agua es gratis.</example>
      <example correction="gratis" type="incorrect">El agua es <marker>de gratis</marker>.</example>
    </rule>
  </category>
  <category name="Palabras de difícil ortografía">
    <rule id="AH_INF" name="ah (a)">
      <pattern case_sensitive="no">
        <token>ah</token>
        <token postag="VMN0000"/>
      </pattern>      
      <message>Esta palabra se escribe sin h: <suggestion>a \2</suggestion>.</message>
      <short>Error ortográfico</short>
      <example correction="a hablar" type="incorrect">Voy <marker>ah hablar</marker> con ella.</example>
      <example type="correct">Voy <marker>a hablar</marker> con ella.</example>
    </rule>
    <rule id="VOY_HA_INF" name="ir ha + infinitivo (a)">
      <pattern>
        <token inflected="yes">ir</token>
        <token>ha</token>
        <token postag="VMN0000"/>
      </pattern>
      <message>Esta palabra se escribe sin h: <suggestion>\1 a \3</suggestion>.</message>
      <short>Error ortográfico</short>
      <example correction="Voy a hablar" type="incorrect"><marker>Voy ha hablar</marker> con ella.</example>
      <example type="correct"><marker>Voy a hablar</marker> con ella.</example>
    </rule>
  </category>
  <category name="ortografia">
    <rule id="Y_I" name="y Italia">
      <pattern case_sensitive="no" mark_to="-1">
        <token>y</token>
        <token regexp="yes">^h?[ií].*</token>
      </pattern>
      <message>Cuando precede a palabras que comienzan por i- (o hi-), la conjunción "y" se transforma en "e": <suggestion>e <match no="2"/></suggestion></message>
      <short>Error ortográfico.</short>
      <example correction="e Italia" type="incorrect">Alemania <marker>y Italia</marker> disputarán el torneo.</example>
      <example type="correct">Alemania <marker>e Italia</marker> disputarán el torneo.</example>
    </rule>
  </category>
</rules>
