=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/rules.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- 
 * LanguageTool, a natural language style checker 
 * Copyright (c) Marcin MiÅ‚kowski, 2009 (http://www.languagetool.org)
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
 * USA
 
 Scheme for rule files
 -->


	<xs:annotation>
		<xs:documentation xml:lang="en"> Main element
		</xs:documentation>
	</xs:annotation>

	<xs:element name="rules">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded" >
				<xs:element ref="unification" />
				<xs:element ref="phrases"/>
				<xs:element ref="category"/>
			</xs:choice>
			<xs:attribute name="lang" type="xs:language" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Unification declarations
		</xs:documentation>
	</xs:annotation>

	<xs:element name="unification">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="equivalence" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="feature" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="equivalence">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="token"/>
			</xs:sequence>
			<xs:attribute name="type" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Phrase-related vocabulary
		</xs:documentation>
	</xs:annotation>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Phrase definitions
		</xs:documentation>
	</xs:annotation>
	<xs:element name="phrases">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phrase" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> individual phrase
			definition </xs:documentation>
	</xs:annotation>
	<xs:element name="phrase">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="unify" />
				<xs:element ref="and" />
				<xs:element ref="token" />
				<xs:element ref="includephrases" />
			</xs:choice>
			<xs:attribute name="id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> OR operator for phrases
		</xs:documentation>
	</xs:annotation>
	<xs:element name="includephrases">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="phraseref" minOccurs='1' maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> element that points to
			the defined phrase </xs:documentation>
	</xs:annotation>
	<xs:element name="phraseref">
		<xs:complexType>
			<xs:attribute name="idref" type="xs:IDREF" use="required" />
		</xs:complexType>
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Use the category element
			to group rules/rulegroups. </xs:documentation>
		<xs:documentation xml:lang="en"> The attribute name shows
			the category use, e.g. 'Grammar', 'Spelling', 'Style' etc.
		</xs:documentation>
	</xs:annotation>

	<xs:element name="category">
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="rule" />
				<xs:element ref="rulegroup" />
			</xs:choice>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Defines a group of rules
			to display several
			rules as one in the configuration user interface. A group has a unique ID.
			The whole rule group can be switched by default off using the
			attribute 'default'.
		</xs:documentation>
	</xs:annotation>
	<xs:element name="rulegroup">
		<xs:complexType>
			<xs:sequence minOccurs="1">
				<xs:element ref="rule" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional" />
			<xs:attribute name="id" type="xs:ID" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> The rule element. The
			unique ID is
			required only if the rule is not contained in a rule group.

			The rule can be switched by default off (using the default attribute).
		</xs:documentation>
	</xs:annotation>
	<xs:element name="rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="pattern" />
				<xs:element ref="message" />
				<xs:element ref="short" minOccurs="0" />								
				<xs:element ref="example" minOccurs="2" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="default" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="off" />
						<xs:enumeration value="on" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" type="xs:string" use="optional" />
			<xs:attribute name="id" type="xs:ID" use="optional" />
		</xs:complexType>
	</xs:element>


	<xs:element name="pattern">
		<xs:complexType>
			<xs:choice minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="token" />
				<xs:element ref="phraseref" />
				<xs:element ref="and" />
				<xs:element ref="unify" />
			</xs:choice>
			<xs:attribute name="mark_from" type="xs:nonNegativeInteger"
				use="optional" />
			<xs:attribute name="mark_to" type="xs:nonPositiveInteger"
				use="optional" />
			<xs:attribute name="case_sensitive" type="binaryYesNo"
				use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="token">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="exception" />
				<xs:element ref="match" />
			</xs:choice>
			<xs:attribute name="postag_regexp" type="binaryYesNo"
				use="optional" default="no" />
			<xs:attribute name="inflected" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="negate" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="regexp" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="spacebefore" use="optional" default="ignore">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="yes" />
						<xs:enumeration value="no" />
						<xs:enumeration value="ignore" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="postag" type="xs:token" use="optional" />
			<xs:attribute name="skip" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="-1" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="negate_pos" type="binaryYesNo" use="optional"
				default="no" />
		</xs:complexType>
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Enables logical AND
			between token elements.  </xs:documentation>
	</xs:annotation>
	<xs:element name="and">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="token" minOccurs="2" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Exception to the matched
			token. </xs:documentation>
	</xs:annotation>

	<xs:element name="exception">
		<xs:complexType mixed="true">
			<xs:attribute name="postag_regexp" type="binaryYesNo" use="optional" default="no" />
			<xs:attribute name="negate_pos" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="postag" type="xs:string" use="optional" />
			<xs:attribute name="spacebefore" use="optional" default="ignore">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="yes" />
						<xs:enumeration value="no" />
						<xs:enumeration value="ignore" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="inflected" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="scope" use="optional" default="current">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="current" />
						<xs:enumeration value="next" />
						<xs:enumeration value="previous" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="regexp" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="negate" type="binaryYesNo" use="optional"
				default="no" />
		</xs:complexType>
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> A short description of
			the error detected by this rule displayed on the
			context menu in OOo.
 </xs:documentation>
	</xs:annotation>
	<xs:element name="short" type="xs:token" />


	<xs:annotation>
		<xs:documentation xml:lang="en"> Message shown to the user
			if a rule matches. </xs:documentation>
	</xs:annotation>
	<xs:element name="message" xml:space="preserve">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="suggestion" />
        <xs:element ref="match" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Suggestion displayed to
			the user. </xs:documentation>
	</xs:annotation>
	<xs:element name="suggestion">
		<xs:complexType mixed="true">
			<xs:sequence minOccurs='0' maxOccurs='unbounded'>
				<xs:element ref="match" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:annotation>
		<xs:documentation xml:lang="en">Reference to the pattern element.
		Might be used in a suggestion or in the pattern.</xs:documentation>
	</xs:annotation>
	<xs:element name="match">
		<xs:complexType mixed="true">
			<xs:attribute name="regexp_match" type="xs:string" use="optional" />
			<xs:attribute name="postag_regexp" type="binaryYesNo"
				use="optional" default="no" />
			<xs:attribute name="setpos" type="binaryYesNo" use="optional"
				default="no" />
			<xs:attribute name="case_conversion" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="startlower" />
						<xs:enumeration value="startupper" />
						<xs:enumeration value="allupper" />
						<xs:enumeration value="alllower" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="regexp_replace" type="xs:string"
				use="optional" />
			<xs:attribute name="postag_replace" type="xs:string"
				use="optional" />
			<xs:attribute name="postag" type="xs:string" use="optional" />
			<xs:attribute name="no" type="xs:nonNegativeInteger"
				use="required" />
			<xs:attribute name="include_skipped" type="includeSelector" use="optional"
				default="none"/> 
		</xs:complexType>
	</xs:element>

	<xs:element name="unify">
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="and" />
				<xs:element ref="token" />
			</xs:choice>
			<xs:attribute name="feature" type="commaSeparated" use="required" />
			<xs:attribute name="type" type="commaSeparated" use="optional" />
			<xs:attribute name="negate" type="binaryYesNo" use="optional"
				default="no" />
		</xs:complexType>
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Specifies examples used
			in JUnit tests and as internal documentation.

			The attribute 'correction' is used to check if the suggested correction
			is correct; multiple
			suggestions are joined with "|".

			The attribute triggers_error is not used.
</xs:documentation>
	</xs:annotation>
	
	<xs:element name="example" xml:space="preserve">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="marker" />
      </xs:choice>
      <xs:attribute name="correction" type="xs:string"
		use="optional" />
      <xs:attribute name="type" use="required">
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="correct" />
            <xs:enumeration value="incorrect" />
            <xs:enumeration value="triggers_error" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="reason" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Marks the matched part of
			the example. </xs:documentation>
	</xs:annotation>
	<xs:element name="marker">
		<xs:complexType mixed="true" />
	</xs:element>


	<xs:annotation>
		<xs:documentation xml:lang="en"> Helper type for binary
			choices. </xs:documentation>
	</xs:annotation>

	<xs:simpleType name="binaryYesNo">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="yes" />
			<xs:enumeration value="no" />
		</xs:restriction>
	</xs:simpleType>

	<xs:annotation>
		<xs:documentation xml:lang="en"> Helper type for match[@include_skipped].
		</xs:documentation>
	</xs:annotation>

	<xs:simpleType name="includeSelector">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="none" />
			<xs:enumeration value="all" />
			<xs:enumeration value="following" />
		</xs:restriction>
	</xs:simpleType>


	<xs:simpleType name="commaSeparated">
		<xs:restriction base="xs:token">
			<xs:pattern value="([^,]+)( *, *[^,]+)*"/>					
		</xs:restriction>
	</xs:simpleType>
	
</xs:schema>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/br/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../print.xsl" ?>
<?xml-stylesheet type="text/css" href="../rules.css"
title="Easy editing stylesheet" ?>
<!--
Breton Grammar and Typo Rules for LanguageTool
Copyright (C) 2011 Dominique Pellé
$Id: grammar.xml,v 1.34 2011-02-12 14:57:58 dominikoeo Exp $
-->
<rules lang="eo"
       xsi:noNamespaceSchemaLocation="../rules.xsd"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Mutations adoucissantes -->
  <category name="Kemmadurioù">
    <rulegroup id="KEMM_DRE_VLOTAAT" name="Kemmadur dre vlotaat">
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">da|ne|pa|re|daou|div|dindan|diwar|dre|eme|gwall|hanter|holl|na|pe|ra|seul|war</token>
          <token regexp="yes">d.*</token>
        </pattern>
        <message>Ur c’hemmadur dre vlotaat a zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="z"/></suggestion> ?</message>
        <example type="incorrect">Re <marker>divalav</marker> eo</example>
        <example type="correct">Re zivalav eo</example>
      </rule>
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">da|ne|pa|re|daou|div|dindan|diwar|dre|eme|gwall|hanter|holl|na|pe|ra|seul|war</token>
          <token regexp="yes">p.*</token>
        </pattern>
        <message>Ur c’hemmadur dre vlotaat a zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="b"/></suggestion> ?</message>
        <example type="incorrect">Ne <marker>plij</marker> ket din komz nederlandeg.</example>
        <example type="correct">Ne blij ket din komz nederlandeg.</example>
      </rule>
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">da|ne|pa|re|daou|div|dindan|diwar|dre|eme|gwall|hanter|holl|na|pe|ra|seul|war</token>
          <token regexp="yes">t.*</token>
        </pattern>
        <message>Ur c’hemmadur dre vlotaat a zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="d"/></suggestion> ?</message>
        <example type="incorrect">Da <marker>tad</marker> a zo er gêr.</example>
        <example type="correct">Da dad a zo er gêr.</example>
      </rule>
    </rulegroup>

    <!-- Mutations spirantes -->
    <rulegroup id="KEMM_DRE_C_HWEZHADENNIN" name="Kemmadur dre c’hwezhadenniñ">
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">ma|va|he|o|em|teir|tri|peder|pevar|nav</token>
          <token regexp="yes">t.*</token>
        </pattern>
        <message>Ur c’hemmadur dre a c’hwezhadenniñ zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="z"/></suggestion> ?</message>
        <example type="incorrect">Va <marker>tad</marker> a gomz brezhoneg.</example>
        <example type="correct">Va zad a gomz brezhoneg.</example>
      </rule>
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">ma|va|he|o|em|teir|tri|peder|pevar|nav</token>
          <token regexp="yes">k.*</token>
        </pattern>
        <message>Ur c’hemmadur dre a c’hwezhadenniñ zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="c’h"/></suggestion> ?</message>
        <example type="incorrect">Tri <marker>karr</marker> em eus.</example>
        <example type="correct">Tri c’harr em eus.</example>
      </rule>
      <rule>
        <pattern mark_from="1">
          <token regexp="yes">ma|va|he|em|teir|tri|peder|pevar|nav</token>
          <token regexp="yes">p.*</token>
        </pattern>
        <message>Ur c’hemmadur dre a c’hwezhadenniñ zlefe bezañ goude ar ger «\1». Fellout a ra deoc’h skrivañ <suggestion><match no="2" regexp_match="." regexp_replace="c’h"/></suggestion> ?</message>
        <example type="incorrect">Re ziwezhat out ma <marker>paotr</marker>!</example>
        <example type="correct">Re ziwezhat out ma faotr!</example>
      </rule>
    </rulegroup>
  </category>

  <!-- Articles -->
  <category name="Gerioù-mell">
    <rule id="AL" name="Ger-mell al/ul/el">
      <pattern mark_to="-1">
        <token regexp="yes">[aeu][nr]</token>
        <token regexp="yes">l.*</token>
      </pattern>
      <message>Ar ger-mell «\1» a zlefe bezañ <suggestion><match no="1" regexp_match="(.)." regexp_replace="$1l"/></suggestion> dirak ur ger a grog gant al gensonnenn «l».</message>
      <example type="incorrect"><marker>Ur</marker> levr a zo ganin.</example>
      <example type="incorrect"><marker>An</marker> levr a zo ganin.</example>
      <example type="correct">Ul levr a zo ganin.</example>
      <example type="correct">Al levr a zo ganin.</example>
      <example type="incorrect">Al levr-mañ emañ <marker>er</marker> levraoueg.</example>
      <example type="correct">Al levr-mañ emañ el levraoueg.</example>
    </rule>
    <rule id="AN" name="Ger-mell an/un/en">
      <pattern mark_to="-1">
        <token regexp="yes">[aeu][lr]</token>
        <token regexp="yes">[ndthaeiou].*</token>
      </pattern>
      <message>A ger mell «\1» a zlefe bezañ <suggestion><match no="1" regexp_match="(.)." regexp_replace="$1n"/></suggestion> dirak ur ger a grog gant al lizherennoù «n, d, t, h, a, e, i, o u».</message>
      <example type="incorrect">Tomm eo <marker>ar</marker> tan.</example>
      <example type="correct">Tomm eo an tan.</example>
    </rule>
    <rule id="AR" name="Ger-mell ar/ur/er">
      <pattern mark_to="-1">
        <token regexp="yes">[aeu][ln]</token>
        <token regexp="yes">[^lndthaeiou0-9].*</token>
      </pattern>
      <message>A ger mell «\1» a zlefe bezañ <suggestion><match no="1" regexp_match="(.)." regexp_replace="$1r"/></suggestion> dirak ur ger na grog ket gant al lizherennoù «n, d, t, h, a, e, i, o u».</message>
      <example type="incorrect"><marker>An</marker> vell-droad a blij din.</example>
      <example type="correct">Ar vell-droad a blij din.</example>
    </rule>
  </category>

</rules>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/el/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../print.xsl" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>

<rules lang="el" xsi:noNamespaceSchemaLocation="../rules.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<category name="Agreement">
		<rule id="HAVE_INF" name="έχω_απαρέμφατο">
			<pattern>
				<token inflected="yes">έχω</token>
				<marker>
					<token postag="V"/>
				</marker>
			</pattern>
			<message>Πιθανόν να χρειάζεται να χρησιμοποιήσετε τον απαρεμφατικό τύπο <suggestion><match no="2" postag="INF"/></suggestion></message>
			<short>Πρόβλημα συμφωνίας</short>
			<example type="incorrect">Είχα <marker>πάω</marker>.</example>
			<example type="correct">Είχα πάει.</example>
		</rule>
	</category>
	<category name="Orthography">
		<rule id="GREEK_WHERE-" name="πού;">
			<pattern>
				<token postag="SENT_START" />
				<marker>
					<token skip="-1">που</token>
				</marker>
				<token>;</token>
			</pattern>
			<message>Στις ερωτηματικές προτάσεις το <suggestion>πού</suggestion> τονίζεται</message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Που</marker> πας;</example>
			<example type="correct">Πού πας;</example>
		</rule>
		<rule id="GREEK_HOW-" name="πώς;">
			<pattern>
				<token postag="SENT_START" />
				<marker>
					<token skip="-1">πως</token>
				</marker>
				<token>;</token>
			</pattern>
			<message>Στις ερωτηματικές προτάσεις το <suggestion>πώς</suggestion> τονίζεται</message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Πως</marker> είσαι;</example>
			<example type="correct">Πώς είσαι;</example>
		</rule>
		<rule id="GREEK_NUMERAL_ONE_WORD" name="αριθμητικά">
			<pattern>
				<token>δέκα</token>
				<token regexp="yes">τρία|τριών|τέσσερα|τέσσερεις|τεσσάρων|πέντε|έξι|επτά|εφτά|οχτώ|οκτώ|εννιά|εννέα</token>
			</pattern>
			<message>Τα αριθμητικά από το 13 μέχρι το 19 γράφονται με μια λέξη <suggestion>δεκα\2</suggestion></message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Δέκα τρία</marker>.</example>
			<example type="correct">Δέκατρία.</example>
		</rule>
		<rule id="GREEK_COMMON_ERRORS_1" name="πώς και πώς">
			<pattern>
				<token>πως</token>
				<token>και</token>
				<token>πως</token>
			</pattern>
			<message><suggestion>πώς και πώς</suggestion></message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Πως και πως</marker>.</example>
			<example type="correct">Πώς και πώς.</example>
		</rule>
		<rule id="GREEK_COMMON_ERRORS_2" name="πού και πού">
			<pattern>
				<token>που</token>
				<token>και</token>
				<token>που</token>
			</pattern>
			<message><suggestion>πού και πού</suggestion></message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Που και που</marker>.</example>
			<example type="correct">Πού και πού.</example>
		</rule>
		<rule id="GREEK_COMMON_ERRORS_3" name="αραιά και πού">
			<pattern>
				<token>αραιά</token>
				<token>και</token>
				<token>που</token>
			</pattern>
			<message><suggestion>αραιά και πού</suggestion></message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect"><marker>Αραιά και που</marker>.</example>
			<example type="correct">Αραιά και πού.</example>
		</rule>
		<rule id="GREEK_COMMON_ERRORS_4" name="πού κι ως πού">
			<pattern>
				<token>που</token>
				<token>κι</token>
				<token>ως</token>
				<token>που</token>
			</pattern>
			<message><suggestion>πού κι ως πού</suggestion></message>
			<short>Πρόβλημα ορθογραφίας</short>
			<example type="incorrect">Από <marker>που κι ως που</marker>.</example>
			<example type="correct">Από πού κι ως πού.</example>
		</rule>
	</category>
</rules>

=== 1371131436/languagetool/trunk/JLanguageTool/src/rules/zh/grammar.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../print.xsl" ?>
<?xml-stylesheet type="text/css" href="../rules.css" 
title="Easy editing stylesheet" ?>
<!--
Chinese Grammar and Typo Rules for LanguageTool
Copyright (C) 2011-2012 Tao Lin
$Id: grammar.xml,v 1.0 2011-07-29 13:20:25 taolin2011 Exp $
-->
<rules lang="en" xsi:noNamespaceSchemaLocation="../rules.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <category name="句法">
    <rulegroup id="s34" name="与中心语搭配不当">
      <rule>
        <pattern mark_to="-1">
          <token skip="-1">许多</token>
          <token>景象</token>
        </pattern>
        <message> ‘景象’不应该与‘（许）多’搭配，您可以使用‘<suggestion>一派</suggestion>’与之搭配。 </message>
        <short>与中心语搭配不当</short>
        <example type="incorrect" correction="一派"> 村里出现了<marker>许多</marker>欣欣向荣的景象。 </example>
        <example type="correct"> 村里出现了<marker>一派</marker>欣欣向荣的景象。 </example>
      </rule>
      <rule>
        <pattern mark_to="-1">
          <token skip="-1">杰出</token>
          <token>意义</token>
        </pattern>
        <message> ‘意义’不应该与‘杰出’搭配，您可以使用‘<suggestion>重大</suggestion>’与之搭配。 </message>
        <short>与中心语搭配不当</short>
        <example type="incorrect" correction="重大"> 《女神》具有<marker>杰出</marker>的历史意义。 </example>
        <example type="correct"> 《女神》是五四运动的产物，具有<marker>重大</marker>的历史意义。 </example>
      </rule>
      <rule>
        <pattern mark_from="1">
          <token skip="-1">照顾</token>
          <token>周全</token>
        </pattern>
        <message> ‘照顾’不应该与‘周全’搭配，您可以使用‘<suggestion>好</suggestion>’与之搭配。 </message>
        <short>与中心语搭配不当</short>
        <example type="incorrect" correction="好"> 上次我对你照顾得太不<marker>周全</marker>。 </example>
        <example type="correct">一定要照顾好妇女和儿童。</example>
      </rule>
    </rulegroup>
    <rulegroup id="s5" name="歧义">
      <rule>
        <pattern>
          <token skip="-1">超过</token>
          <token skip="-1" postag="u">的</token>
          <token regexp="yes" postag="m|q" postag_regexp="yes">百分之.*|倍</token>
        </pattern>
        <message>‘超过’造成的歧义。</message>
        <short>歧义</short>
        <example type="incorrect"> 实际生产的量<marker>超过了计划的百分之百</marker>。 </example>
        <example type="correct">实际产量远远超过了计划产量。</example>
      </rule>
      <rule>
        <pattern>
          <token postag="m"/>
          <token postag="q"/>
          <token postag="n"/>
          <token>、</token>
        </pattern>
        <message>数量词修饰并列短语，可能产生歧义</message>
        <short>语法错误</short>
        <example type="incorrect">
          <marker>3个领导、</marker>书记 </example>
        <example type="correct">3个市长来到了我们县。</example>
      </rule>
      <rule>
        <pattern mark_to="-1">
          <token postag="m"/>
          <token postag="q"/>
          <token postag="n"/>
          <token postag="c" regexp="yes" skip="5"> [和与及同跟既]<exception postag="m|q"
              postag_regexp="yes" scope="next"/>
          </token>
          <token postag="n">
            <exception postag="v|p" postag_regexp="yes" scope="previous"/>
          </token>
          <token postag="n.*|vn|q" postag_regexp="yes" negate_pos="yes"/>
        </pattern>
        <message>数量词修饰并列短语，可能产生歧义</message>
        <short>语法错误</short>
        <example type="incorrect">
          <marker>3个领导和书记</marker>莅临视察。 </example>
        <example type="correct">3个市长和3个书记莅临我校指导工作。</example>
      </rule>
    </rulegroup>
  </category>
</rules>
